FROM mcr.microsoft.com/devcontainers/base:bullseye

RUN curl -LO https://github.com/OpenSlides/openslides-manage-service/releases/download/latest/openslides && chmod +x openslides && mv openslides /usr/local/bin
